/* Drive & Shine Command Center — interactive client-side application */
const STORAGE_KEY = "drive-shine-command-center-v1";

const seed = {
  bookings: [
    { id: "BK-240630", customer: "John Mensah", phone: "024 563 8194", vehicle: "Mercedes GLE 450", package: "Premium Detail", date: "2024-06-30", time: "10:30 AM", price: 850, payment: "Paid", status: "Confirmed", initials: "JM" },
    { id: "BK-240629", customer: "Michael Owusu", phone: "055 831 7280", vehicle: "Toyota Land Cruiser", package: "Full Service Wash", date: "2024-06-30", time: "12:00 PM", price: 350, payment: "Paid", status: "In Progress", initials: "MO" },
    { id: "BK-240628", customer: "Abigail Boateng", phone: "020 486 2504", vehicle: "Range Rover Sport", package: "Gold Membership", date: "2024-06-30", time: "02:30 PM", price: 1200, payment: "Pending", status: "Assigned", initials: "AB" },
    { id: "BK-240627", customer: "Evelyn Asante", phone: "024 124 9163", vehicle: "BMW X5", package: "Interior Cleaning", date: "2024-06-29", time: "09:00 AM", price: 450, payment: "Paid", status: "Completed", initials: "EA" },
    { id: "BK-240626", customer: "Kwame Addo", phone: "054 345 8271", vehicle: "Lexus RX 350", package: "Engine Bay Clean", date: "2024-06-29", time: "11:00 AM", price: 280, payment: "Paid", status: "Completed", initials: "KA" },
    { id: "BK-240625", customer: "Rita Ofori", phone: "027 100 4848", vehicle: "Honda Accord", package: "Premium Detail", date: "2024-06-29", time: "03:00 PM", price: 850, payment: "Pending", status: "Pending", initials: "RO" },
    { id: "BK-240624", customer: "Daniel Kusi", phone: "050 583 4718", vehicle: "Ford Ranger", package: "Full Service Wash", date: "2024-06-28", time: "10:00 AM", price: 350, payment: "Paid", status: "Completed", initials: "DK" },
    { id: "BK-240623", customer: "Nana Agyeman", phone: "024 965 1204", vehicle: "Audi Q7", package: "Platinum Membership", date: "2024-06-28", time: "01:30 PM", price: 1800, payment: "Paid", status: "Completed", initials: "NA" }
  ],
  customers: [
    { name: "John Mensah", phone: "024 563 8194", email: "john.mensah@email.com", address: "East Legon, Accra", membership: "Gold", spent: 8450, service: "30 Jun 2024", status: "Active", joined: "12 Mar 2023", initials: "JM" },
    { name: "Michael Owusu", phone: "055 831 7280", email: "m.owusu@email.com", address: "Airport Residential, Accra", membership: "Platinum", spent: 12400, service: "30 Jun 2024", status: "Active", joined: "07 Aug 2022", initials: "MO" },
    { name: "Abigail Boateng", phone: "020 486 2504", email: "abigail.b@email.com", address: "Cantonments, Accra", membership: "Gold", spent: 6200, service: "30 Jun 2024", status: "Active", joined: "21 Jan 2024", initials: "AB" },
    { name: "Evelyn Asante", phone: "024 124 9163", email: "evelyn.a@email.com", address: "Osu, Accra", membership: "Silver", spent: 3250, service: "29 Jun 2024", status: "Active", joined: "19 May 2024", initials: "EA" },
    { name: "Kwame Addo", phone: "054 345 8271", email: "k.addo@email.com", address: "Dzorwulu, Accra", membership: "—", spent: 1870, service: "29 Jun 2024", status: "Active", joined: "02 Apr 2024", initials: "KA" },
    { name: "Rita Ofori", phone: "027 100 4848", email: "rita.ofori@email.com", address: "Spintex, Accra", membership: "—", spent: 850, service: "29 Jun 2024", status: "Active", joined: "28 Jun 2024", initials: "RO" },
    { name: "Daniel Kusi", phone: "050 583 4718", email: "daniel.k@email.com", address: "Adenta, Accra", membership: "Silver", spent: 4100, service: "28 Jun 2024", status: "Active", joined: "10 Nov 2023", initials: "DK" },
    { name: "Nana Agyeman", phone: "024 965 1204", email: "n.agyeman@email.com", address: "Labone, Accra", membership: "Platinum", spent: 16300, service: "28 Jun 2024", status: "Active", joined: "15 Jul 2022", initials: "NA" }
  ],
  inventory: [
    { item: "Wheel Cleaner", category: "Chemicals", quantity: 2, unit: "bottles", minimum: 5, cost: 75, supplier: "AutoChem Ghana", status: "Critical", last: "18 Jun 2024" },
    { item: "Microfiber Towels", category: "Microfiber Towels", quantity: 12, unit: "pieces", minimum: 20, cost: 12, supplier: "Detail Supply Co.", status: "Low", last: "21 Jun 2024" },
    { item: "Snow Foam", category: "Chemicals", quantity: 4, unit: "bottles", minimum: 6, cost: 85, supplier: "AutoChem Ghana", status: "Low", last: "24 Jun 2024" },
    { item: "Dual Action Polisher", category: "Machines", quantity: 3, unit: "units", minimum: 2, cost: 950, supplier: "Pro Detail Tools", status: "Normal", last: "10 Jun 2024" },
    { item: "Leather Conditioner", category: "Chemicals", quantity: 8, unit: "bottles", minimum: 4, cost: 68, supplier: "AutoChem Ghana", status: "Normal", last: "26 Jun 2024" },
    { item: "Interior Brushes", category: "Tools", quantity: 11, unit: "sets", minimum: 4, cost: 45, supplier: "Pro Detail Tools", status: "Normal", last: "08 Jun 2024" },
    { item: "Nitrile Gloves", category: "Consumables", quantity: 6, unit: "boxes", minimum: 8, cost: 40, supplier: "Detail Supply Co.", status: "Low", last: "20 Jun 2024" },
    { item: "Glass Cleaner", category: "Chemicals", quantity: 9, unit: "bottles", minimum: 4, cost: 48, supplier: "AutoChem Ghana", status: "Normal", last: "12 Jun 2024" }
  ],
  payments: [
    { invoice: "INV-2024-1025", customer: "Michael Owusu", date: "30 Jun 2024", amount: 350, method: "Card", status: "Paid", booking: "BK-240629" },
    { invoice: "INV-2024-1024", customer: "John Mensah", date: "30 Jun 2024", amount: 850, method: "MTN Mobile Money", status: "Paid", booking: "BK-240630" },
    { invoice: "INV-2024-1023", customer: "Abigail Boateng", date: "30 Jun 2024", amount: 1200, method: "Bank Transfer", status: "Pending", booking: "BK-240628" },
    { invoice: "INV-2024-1022", customer: "Evelyn Asante", date: "29 Jun 2024", amount: 450, method: "Cash", status: "Paid", booking: "BK-240627" },
    { invoice: "INV-2024-1021", customer: "Kwame Addo", date: "29 Jun 2024", amount: 280, method: "Telecel Cash", status: "Paid", booking: "BK-240626" },
    { invoice: "INV-2024-1020", customer: "Rita Ofori", date: "29 Jun 2024", amount: 850, method: "AirtelTigo Money", status: "Pending", booking: "BK-240625" }
  ],
  memberships: [
    { customer: "John Mensah", plan: "Gold", start: "12 Jun 2024", expiry: "12 Jul 2024", status: "Active", renewal: "12 Jul 2024", price: 1200 },
    { customer: "Michael Owusu", plan: "Platinum", start: "01 Jun 2024", expiry: "01 Jul 2024", status: "Expiring", renewal: "01 Jul 2024", price: 1800 },
    { customer: "Abigail Boateng", plan: "Gold", start: "30 Jun 2024", expiry: "30 Jul 2024", status: "Active", renewal: "30 Jul 2024", price: 1200 },
    { customer: "Evelyn Asante", plan: "Silver", start: "19 Jun 2024", expiry: "19 Jul 2024", status: "Active", renewal: "19 Jul 2024", price: 650 },
    { customer: "Daniel Kusi", plan: "Silver", start: "10 Jun 2024", expiry: "10 Jul 2024", status: "Active", renewal: "10 Jul 2024", price: 650 }
  ],
  notifications: [
    { id: 1, type: "booking", icon: "calendar-plus", title: "New booking received", text: "John Mensah booked Premium Detail for today.", time: "10:30 AM", read: false },
    { id: 2, type: "payment", icon: "wallet-cards", title: "Payment received", text: "GHS 350.00 received from Michael Owusu.", time: "09:45 AM", read: false },
    { id: 3, type: "membership", icon: "crown", title: "Membership renewed", text: "Abigail Boateng renewed her Gold Plan.", time: "08:30 AM", read: false },
    { id: 4, type: "inventory", icon: "triangle-alert", title: "Inventory alert", text: "Wheel Cleaner has only 2 bottles left in stock.", time: "07:15 AM", read: false },
    { id: 5, type: "booking", icon: "calendar-check", title: "Booking completed", text: "Daniel Kusi's Full Service Wash was completed.", time: "Yesterday", read: true },
    { id: 6, type: "system", icon: "badge-check", title: "Daily report ready", text: "Your 29 June operations report is ready to review.", time: "Yesterday", read: true },
    { id: 7, type: "payment", icon: "circle-dollar-sign", title: "Payment pending", text: "Rita Ofori has an outstanding invoice of GHS 850.00.", time: "Yesterday", read: false },
    { id: 8, type: "membership", icon: "clock-3", title: "Membership expiring", text: "Michael Owusu's Platinum Plan renews tomorrow.", time: "Yesterday", read: false }
  ]
};

let store = loadStore();
let currentPage = "dashboard";
let bookingFilter = "All";
let localFilter = "";
let notificationFilter = "All";

const pageRoot = document.getElementById("pageRoot");
const appShell = document.getElementById("appShell");
const modalOverlay = document.getElementById("modalOverlay");
const recordForm = document.getElementById("recordForm");
const toastStack = document.getElementById("toastStack");

function loadStore() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (!saved) return structuredClone(seed);
    const restored = JSON.parse(saved);
    const completeStore = structuredClone(seed);
    Object.keys(seed).forEach((key) => {
      if (Array.isArray(restored[key])) completeStore[key] = restored[key];
    });
    return completeStore;
  } catch { return structuredClone(seed); }
}
function saveStore() { localStorage.setItem(STORAGE_KEY, JSON.stringify(store)); }
function escapeHtml(value = "") { return String(value).replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#039;",'"':"&quot;"}[c])); }
function formatMoney(value) { return `GHS ${Number(value).toLocaleString("en-GH", {minimumFractionDigits: 2, maximumFractionDigits: 2})}`; }
function initials(name) { return name.split(" ").slice(0,2).map(x=>x[0]).join("").toUpperCase(); }
function statusClass(status) { return status.toLowerCase().replaceAll(" ", "-"); }
function icon(name, extra = "") { return `<i data-lucide="${name}"${extra ? ` class="${extra}"` : ""}></i>`; }
function refreshIcons() { if (window.lucide) window.lucide.createIcons(); }
function unreadCount() { return store.notifications.filter(n => !n.read).length; }

function metricCard(iconName, tone, label, value, change, sub, danger = false) {
  return `<article class="metric-card"><div class="metric-top"><span class="metric-icon ${tone}">${icon(iconName)}</span><div><div class="metric-label">${label}</div><div class="metric-value">${value}</div></div></div><div class="metric-meta"><b class="${danger ? "danger" : ""}">${change}</b><span>${sub}</span></div></article>`;
}
function pageHeader(title, subtitle, actions = "") { return `<header class="page-header"><div><h1>${title}</h1><p>${subtitle}</p></div>${actions ? `<div class="header-actions">${actions}</div>` : ""}</header>`; }
function dateControl() { return `<button class="date-button" type="button" data-action="choose-date">${icon("calendar-days")} Tuesday, 25 June 2024 ${icon("chevron-down")}</button>`; }
function statusBadge(value) { return `<span class="status ${statusClass(value)}">${escapeHtml(value)}</span>`; }
function tinyAvatar(name, existing) { return `<span class="tiny-avatar">${escapeHtml(existing || initials(name))}</span>`; }

function revenueChart() {
  return `<div class="revenue-chart"><div class="chart-grid"><span><b>80K</b></span><span><b>60K</b></span><span><b>40K</b></span><span><b>20K</b></span></div><svg class="area-svg" viewBox="0 0 580 145" preserveAspectRatio="none" aria-label="Revenue trend chart"><defs><linearGradient id="goldFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#f5bd2a" stop-opacity=".42"/><stop offset="100%" stop-color="#f5bd2a" stop-opacity=".015"/></linearGradient></defs><path class="line-fill" d="M0 126 C15 121 19 103 35 109 S58 109 71 86 S100 94 116 83 S143 87 158 65 S184 72 200 61 S233 70 251 59 S277 69 296 53 S322 60 338 55 S362 57 378 47 S403 59 421 37 S450 52 466 38 S493 19 513 33 S545 32 562 24 S577 30 580 27 L580 145 L0 145 Z"/><path class="line-stroke" d="M0 126 C15 121 19 103 35 109 S58 109 71 86 S100 94 116 83 S143 87 158 65 S184 72 200 61 S233 70 251 59 S277 69 296 53 S322 60 338 55 S362 57 378 47 S403 59 421 37 S450 52 466 38 S493 19 513 33 S545 32 562 24 S577 30 580 27"/><circle class="chart-dot" cx="279" cy="62" r="4" /></svg><span class="chart-vertical"></span><div class="chart-tooltip"><span>15 June 2024</span><b>GHS 45,650.00</b></div><div class="axis-labels"><span>1 Jun</span><span>5 Jun</span><span>10 Jun</span><span>15 Jun</span><span>20 Jun</span><span>25 Jun</span><span>30 Jun</span></div></div>`;
}
function bookingChart() {
  const vals = [35,22,37,48,23,31,20,27,40,55,67,43,32,22,16,48,70,29,42,59,34,20,15,39,58];
  return `<div class="bar-chart">${vals.map((v,i)=>`<span class="bar" style="--h:${v}%" data-value="${Math.round(v/4)} bookings"></span>`).join("")}</div><div class="bar-labels"><span>1 Jun</span><span>5 Jun</span><span>10 Jun</span><span>15 Jun</span><span>20 Jun</span><span>25 Jun</span><span>30 Jun</span></div>`;
}
function donutChart() { return `<div class="package-layout"><div class="donut-wrap"><svg class="donut" viewBox="0 0 140 140"><circle class="ring-bg" cx="70" cy="70" r="52"></circle><circle class="seg-1" cx="70" cy="70" r="52"></circle><circle class="seg-2" cx="70" cy="70" r="52"></circle><circle class="seg-3" cx="70" cy="70" r="52"></circle><circle class="seg-4" cx="70" cy="70" r="52"></circle><circle class="seg-5" cx="70" cy="70" r="52"></circle></svg><div class="donut-center"><span>Total</span><b>150</b></div></div><div class="legend"><div class="legend-item"><i class="legend-dot" style="background:#f2bd2d"></i><span>Premium Detail</span><b>40%</b></div><div class="legend-item"><i class="legend-dot" style="background:#7847cd"></i><span>Interior Cleaning</span><b>25%</b></div><div class="legend-item"><i class="legend-dot" style="background:#3a73ce"></i><span>Full Service Wash</span><b>20%</b></div><div class="legend-item"><i class="legend-dot" style="background:#4aa14c"></i><span>Engine Bay Clean</span><b>10%</b></div><div class="legend-item"><i class="legend-dot" style="background:#7f858c"></i><span>Other Services</span><b>5%</b></div></div></div>`; }

function dashboardPage() {
  const metrics = [
    ["circle-dollar-sign","gold","Today’s Revenue",formatMoney(2450),"+12.5%","vs yesterday"], ["chart-no-axes-combined","gold","Weekly Revenue",formatMoney(15650),"+8.2%","vs last week"], ["calendar-range","gold","Monthly Revenue",formatMoney(68750),"+15.7%","vs last month"], ["calendar-check-2","purple","Bookings Today","15","+3","vs yesterday"], ["circle-check-big","green","Completed Jobs","10","66.7%","completion rate"],
    ["clock-3","orange","Pending Jobs","5","33.3%","remaining"], ["user-round-plus","blue","New Customers","4","+2","vs yesterday"], ["refresh-cw","teal","Repeat Customers","18","+4","vs last week"], ["crown","purple","Active Memberships","23","+3","vs last week"], ["triangle-alert","red","Low Inventory Alerts","3","—","Items running low", true]
  ];
  const activity = [
    ["calendar-plus","gold","New booking received from John Mensah","Premium Detail - Toyota Prado","10:30 AM"], ["wallet-cards","green","Payment of GHS 350.00 received from Michael Owusu","Invoice INV-2024-1025","09:45 AM"], ["crown","red","Membership renewed by Abigail Boateng","Gold Plan","08:30 AM"], ["bell-ring","orange","Inventory alert: Wheel Cleaner is running low","Only 2 items left in stock","07:15 AM"]
  ];
  return `<section class="page-transition">${pageHeader("Welcome back, Admin 👋", "Here’s what’s happening with your business today.", dateControl())}<div class="kpi-grid">${metrics.map(m=>metricCard(...m)).join("")}</div><div class="dashboard-charts"><section class="panel chart-panel"><div class="panel-header"><h2>Revenue Trend</h2><button class="chart-select" type="button" data-action="change-chart">This Month ${icon("chevron-down")}</button></div>${revenueChart()}</section><section class="panel chart-panel"><div class="panel-header"><h2>Booking Trend</h2><button class="chart-select" type="button" data-action="change-chart">This Month ${icon("chevron-down")}</button></div>${bookingChart()}</section><section class="panel chart-panel package-panel"><div class="panel-header"><h2>Popular Packages</h2></div>${donutChart()}</section></div><div class="dashboard-bottom"><section class="panel activity-panel"><div class="panel-header"><h2>Recent Activity</h2></div><div class="activity-list">${activity.map(row=>`<div class="activity-row"><span class="activity-icon ${row[1]}-icon" style="color:var(--${row[1]});background:var(--${row[1]}-bg)">${icon(row[0])}</span><div class="activity-content"><p>${row[2]}</p><span>${row[3]}</span></div><time class="activity-time">${row[4]}</time></div>`).join("")}</div><button class="view-activity" type="button" data-page="notifications">View all activity ${icon("chevron-right")}</button></section><section class="panel quick-panel"><div class="panel-header"><h2>Quick Actions</h2></div><div class="quick-actions"><button class="quick-action" type="button" data-open-modal="booking"><span class="quick-icon">${icon("calendar-plus")}</span><span>New Booking</span></button><button class="quick-action" type="button" data-open-modal="customer"><span class="quick-icon">${icon("user-round-plus")}</span><span>Add Customer</span></button><button class="quick-action" type="button" data-open-modal="payment"><span class="quick-icon">${icon("credit-card")}</span><span>Record Payment</span></button><button class="quick-action" type="button" data-open-modal="inventory"><span class="quick-icon">${icon("box")}</span><span>Add Inventory</span></button><button class="quick-action" type="button" data-page="reports"><span class="quick-icon">${icon("file-chart-column")}</span><span>Generate Report</span></button></div></section></div></section>`;
}

function filtered(items, keys) { const q = localFilter.toLowerCase(); return !q ? items : items.filter(item => keys.some(key => String(item[key] || "").toLowerCase().includes(q))); }
function bookingTable(rows) {
  return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Booking ID</th><th>Customer</th><th>Vehicle</th><th>Package</th><th>Date &amp; Time</th><th>Price</th><th>Payment</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length ? rows.map(b=>`<tr><td><strong>${b.id}</strong></td><td><div class="customer-cell">${tinyAvatar(b.customer,b.initials)}<div><strong>${escapeHtml(b.customer)}</strong><span class="subtext">${escapeHtml(b.phone)}</span></div></div></td><td>${escapeHtml(b.vehicle)}</td><td>${escapeHtml(b.package)}</td><td>${b.date}<span class="subtext">${b.time}</span></td><td>${formatMoney(b.price)}</td><td>${statusBadge(b.payment)}</td><td>${statusBadge(b.status)}</td><td><div class="row-actions"><button class="row-action" title="View booking" data-action="view-booking" data-id="${b.id}">${icon("eye")}</button><button class="row-action" title="Delete booking" data-action="delete-booking" data-id="${b.id}">${icon("trash-2")}</button></div></td></tr>`).join("") : `<tr><td colspan="9"><div class="empty-state">No bookings match your current filters.</div></td></tr>`}</tbody></table></div><div class="pagination"><span>Showing ${rows.length} of ${store.bookings.length} bookings</span><div class="pagination-buttons"><button class="page-dot active">1</button><button class="page-dot">2</button><button class="page-dot">›</button></div></div>`;
}
function bookingsPage() {
  let rows = bookingFilter === "All" ? store.bookings : store.bookings.filter(b => b.status === bookingFilter);
  rows = filtered(rows,["id","customer","phone","vehicle","package","status","payment"]);
  const tabs = ["All","Pending","Confirmed","Assigned","In Progress","Completed","Cancelled"];
  return `<section class="page-transition">${pageHeader("Bookings", "Schedule, track, and manage every customer appointment.", `<button class="outline-button" type="button" data-action="export">${icon("download")} Export</button><button class="primary-button" type="button" data-open-modal="booking">${icon("plus")} Create Booking</button>`)}<div class="toolbar"><label class="local-search">${icon("search")}<input id="localSearch" value="${escapeHtml(localFilter)}" placeholder="Search bookings, customer, vehicle..." /></label><div class="toolbar-actions"><button class="filter-button" type="button" data-action="filter-info">${icon("list-filter")} Filters</button><button class="filter-button" type="button" data-action="columns">${icon("columns-3")} Columns</button></div></div><div class="tabs">${tabs.map(tab=>`<button class="tab ${bookingFilter===tab?"active":""}" type="button" data-booking-tab="${tab}">${tab}${tab === "Pending" ? " (5)" : ""}</button>`).join("")}</div><section class="panel data-panel">${bookingTable(rows)}</section></section>`;
}

function calendarPage() {
  const dates = ["26","27","28","29","30","31","1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","1","2","3","4","5","6"];
  const events = { 4:["10:30 John M.","2:00 Rita O."], 5:["12:00 Michael O."], 10:["9:00 Evelyn A."], 12:["1:30 Nana A."], 16:["11:00 Kwame A."], 20:["10:00 John M."], 25:["12:00 Abigail B."], 30:["9:30 Michael O."] };
  return `<section class="page-transition">${pageHeader("Calendar", "View availability and manage your team’s mobile detailing schedule.", `<button class="outline-button" type="button" data-action="calendar-view">${icon("calendar-range")} Month</button><button class="primary-button" type="button" data-open-modal="booking">${icon("plus")} New Booking</button>`)}<section class="panel calendar-card"><div class="calendar-toolbar"><div class="calendar-nav"><button type="button" data-action="month-nav">${icon("chevron-left")}</button><h2>June 2024</h2><button type="button" data-action="month-nav">${icon("chevron-right")}</button></div><div class="tabs" style="margin:0"><button class="tab" type="button" data-action="calendar-view">Day</button><button class="tab" type="button" data-action="calendar-view">Week</button><button class="tab active" type="button" data-action="calendar-view">Month</button><button class="tab" type="button" data-action="calendar-view">Agenda</button></div></div><div class="calendar-grid">${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="calendar-weekday">${d}</div>`).join("")}${dates.map((day,i)=>{ const muted=i<6||i>35; const today=day==="25"; const list=events[i]||[]; return `<div class="calendar-day ${muted?"muted":""} ${today?"today":""}"><span class="day-number">${day}</span>${list.map((x,j)=>`<button class="calendar-event ${["gold","green","purple","blue"][(i+j)%4]}" type="button" data-action="calendar-event">${x}</button>`).join("")}</div>`; }).join("")}</div></section></section>`;
}

function inventoryPage() { syncDerivedData(); const rows=filtered(store.inventory,["item","category","supplier","status"]); const low=store.inventory.filter(i=>i.status!=="Normal"); return `<section class="page-transition">${pageHeader("Inventory", "Track supplies, stock usage, and replenishment in one place.", `<button class="outline-button" type="button" data-action="inventory-history">${icon("history")} History</button><button class="primary-button" type="button" data-open-modal="inventory">${icon("plus")} Add Item</button>`)}<div class="inventory-alerts"><section class="panel alert-summary"><span class="metric-icon red">${icon("triangle-alert")}</span><div><h3>${low.length} low-stock alert${low.length===1?"":"s"}</h3><p>Items at or below their minimum level.</p></div></section><section class="panel alert-summary"><span class="metric-icon gold">${icon("package-check")}</span><div><h3>${store.inventory.length} tracked items</h3><p>${store.inventory.filter(i=>i.status==="Normal").length} items have healthy stock.</p></div></section></div><div class="toolbar"><label class="local-search">${icon("search")}<input id="localSearch" value="${escapeHtml(localFilter)}" placeholder="Search inventory..." /></label><div class="toolbar-actions"><button class="filter-button" type="button" data-action="export">${icon("download")} Export CSV</button></div></div><section class="panel data-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Item Name</th><th>Category</th><th>Quantity</th><th>Minimum Stock</th><th>Unit Cost</th><th>Total Value</th><th>Supplier</th><th>Last Updated</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map(i=>{const index=store.inventory.indexOf(i);return `<tr><td><strong>${escapeHtml(i.item)}</strong></td><td>${escapeHtml(i.category)}</td><td>${i.quantity} ${escapeHtml(i.unit)}</td><td>${i.minimum} ${escapeHtml(i.unit)}</td><td>${formatMoney(i.cost)}</td><td>${formatMoney(i.quantity*i.cost)}</td><td>${escapeHtml(i.supplier)}</td><td>${displayDate(i.last)}</td><td>${statusBadge(i.status)}</td><td><div class="row-actions"><button class="row-action" data-action="stock-out" data-index="${index}" title="Use item">${icon("minus-circle")}</button><button class="row-action" data-action="restock" data-index="${index}" title="Restock">${icon("package-plus")}</button></div></td></tr>`}).join("") || `<tr><td colspan="10"><div class="empty-state">No inventory items found.</div></td></tr>`}</tbody></table></div></section></section>`; }

function profilePage() { const profile=store.profile || {fullName:"Admin Mensah",email:"admin@driveandshine.com",phone:"024 000 0000",role:"Super Admin",preferences:{booking:true,inventory:true,twoFactor:false}}; const photo=profile.photo ? `<img src="${profile.photo}" alt="Profile photo" class="profile-avatar" />` : `<span class="avatar profile-avatar avatar-main">${initials(profile.fullName)}</span>`; return `<section class="page-transition">${pageHeader("Profile & Settings", "Manage your account, security, and notification preferences.")}<div class="profile-layout"><aside class="panel profile-card">${photo}<h2>${escapeHtml(profile.fullName)}</h2><p>${escapeHtml(profile.email)}</p><div class="profile-badges">${statusBadge("Active")}<span class="status confirmed">${escapeHtml(profile.role)}</span></div><div class="form-actions"><label class="outline-button" style="cursor:pointer">${icon("image-up")} Upload photo<input id="profilePhoto" type="file" accept="image/png,image/jpeg,image/webp" hidden /></label>${profile.photo?`<button class="outline-button" type="button" data-action="remove-photo">Remove</button>`:""}</div></aside><section class="panel profile-form"><h2>Personal information</h2><form id="profileForm"><div class="form-grid"><label class="form-field"><span>Full Name</span><input name="fullName" value="${escapeHtml(profile.fullName)}" required /></label><label class="form-field"><span>Email Address</span><input name="email" type="email" value="${escapeHtml(profile.email)}" required /></label><label class="form-field"><span>Phone Number</span><input name="phone" value="${escapeHtml(profile.phone)}" required /></label><label class="form-field"><span>Role</span><input value="${escapeHtml(profile.role)}" disabled /></label></div><div class="form-section"><h3>Preferences</h3>${[["booking","Booking notifications","Receive updates for new bookings."],["inventory","Inventory alerts","Notify when stock reaches its minimum."],["twoFactor","Two-factor authentication","Add a second verification step."]].map(([key,title,desc])=>`<div class="setting-row"><div><b>${title}</b><span>${desc}</span></div><button class="toggle ${profile.preferences[key]?"on":""}" data-preference="${key}" type="button"></button></div>`).join("")}</div><div class="form-actions"><button class="outline-button" type="button" data-action="password">Change Password</button><button class="primary-button" type="submit">${icon("save")} Save Changes</button></div></form></section></div></section>`; }

function receipt(payment) { const booking=store.bookings.find(b=>b.id===payment.booking); const contact=store.profile || {}; return `<section class="receipt-print"><h1>Drive & Shine</h1><p>Premium mobile detailing · ${escapeHtml(contact.phone || "024 087 1412")}</p><hr><h2>Payment Receipt</h2><p><b>Receipt:</b> ${escapeHtml(payment.invoice)}<br><b>Date:</b> ${displayDate(payment.date)}<br><b>Customer:</b> ${escapeHtml(payment.customer)}<br><b>Booking:</b> ${escapeHtml(payment.booking || "—")}<br><b>Service:</b> ${escapeHtml(booking?.package || "Service payment")}<br><b>Method:</b> ${escapeHtml(payment.method)}</p><h2>Total paid: ${formatMoney(payment.amount)}</h2><p>Thank you for choosing Drive & Shine.</p></section>`; }

function showReceipt(index) { const payment=store.payments[index]; if(!payment) return; const win=window.open("", "_blank", "noopener,noreferrer"); if(!win){showToast("Pop-up blocked","Allow pop-ups to print the receipt.","error");return;} win.document.write(`<!doctype html><html><head><title>Receipt ${escapeHtml(payment.invoice)}</title><style>body{font-family:Arial;max-width:540px;margin:36px auto;color:#111}.receipt-print{border:1px solid #ddd;padding:28px}h1{margin-bottom:2px}hr{border:0;border-top:1px solid #ddd;margin:22px 0}</style></head><body>${receipt(payment)}<script>window.onload=()=>window.print();<\/script></body></html>`); win.document.close(); }

function openStockOut(index) { const item=store.inventory[index]; if(!item)return; document.getElementById("modalEyebrow").textContent="Inventory usage"; document.getElementById("modalTitle").textContent=`Use ${item.item}`; recordForm.dataset.type="stock-out"; recordForm.dataset.index=index; recordForm.innerHTML=`<p class="note-box">Available: <strong>${item.quantity} ${escapeHtml(item.unit)}</strong></p><div class="form-grid">${field("Quantity to remove","quantity","number","0")} ${field("Reason","reason","textarea","e.g. Used for booking BK-...")}</div><div class="form-actions"><button class="outline-button" type="button" id="modalCancel">Cancel</button><button class="primary-button" type="submit">${icon("minus-circle")} Record stock out</button></div>`; modalOverlay.classList.add("open"); modalOverlay.setAttribute("aria-hidden","false"); refreshIcons(); }

function handleRecordSubmit(e) { e.preventDefault(); const type=recordForm.dataset.type; if(type==="plan"){closeModal();return;} if(!validateRecordForm()){showToast("Check required fields","Please complete required fields.","error");return;} const fd=Object.fromEntries(new FormData(recordForm).entries());
  if(type==="stock-out") { const item=store.inventory[Number(recordForm.dataset.index)], qty=Number(fd.quantity); if(!item || !Number.isFinite(qty) || qty<=0 || qty>item.quantity || !fd.reason.trim()){showToast("Unable to record stock out",`Enter a quantity from 1 to ${item?.quantity||0} and a reason.`,"error");return;} item.quantity-=qty; item.last=isoDate(); item.status=statusForStock(item); addTransaction(item,"Out",qty,fd.reason.trim()); showToast("Stock usage recorded",`${qty} ${item.unit} removed from ${item.item}.`); }
  if(type==="booking") { if(!/^\d{4}-\d{2}-\d{2}$/.test(fd.date) || !/^[-+() 0-9]{7,}$/.test(fd.phone)){showToast("Invalid booking","Use a valid date and phone number.","error");return;} const current=store.bookings.find(b=>b.id===recordForm.dataset.editId); const data={customer:fd.customer.trim(),phone:fd.phone.trim(),vehicle:fd.vehicle.trim(),package:fd.package,date:fd.date,time:fd.time,price:Number(fd.price),initials:initials(fd.customer)}; if(current)Object.assign(current,data);else{const id=`BK-${Date.now().toString().slice(-7)}`;store.bookings.unshift({id,...data,payment:"Pending",status:"Pending"});if(!store.customers.some(c=>c.name.toLowerCase()===data.customer.toLowerCase()))store.customers.unshift({name:data.customer,phone:data.phone,email:"—",address:"—",membership:"—",spent:0,service:"New booking",status:"Active",joined:isoDate(),initials:data.initials});} showToast(current?"Booking updated":"Booking created",`${data.customer}'s schedule is synchronized.`); }
  if(type==="customer") { if(!/^[-+() 0-9]{7,}$/.test(fd.phone)||!/^\S+@\S+\.\S+$/.test(fd.email)){showToast("Invalid customer","Enter a valid phone number and email.","error");return;} if(store.customers.some(c=>c.email.toLowerCase()===fd.email.toLowerCase())){showToast("Duplicate customer","That email already belongs to a customer.","error");return;}store.customers.unshift({name:fd.name,phone:fd.phone,email:fd.email,address:fd.address,membership:fd.membership||"—",spent:0,service:"No services",status:"Active",joined:isoDate(),initials:initials(fd.name)});showToast("Customer added",`${fd.name} is now in your customer list.`); }
  if(type==="payment") { if(Number(fd.amount)<=0 || !fd.date){showToast("Invalid payment","Enter a valid date and amount.","error");return;}const invoice=`INV-${new Date().getFullYear()}-${String(1000+store.payments.length+1)}`;store.payments.unshift({invoice,customer:fd.customer,date:fd.date,amount:Number(fd.amount),method:fd.method,status:"Paid",booking:fd.booking||"—"});const customer=store.customers.find(c=>c.name.toLowerCase()===fd.customer.toLowerCase());if(customer)customer.spent=Number(customer.spent||0)+Number(fd.amount);showToast("Payment recorded",`${formatMoney(fd.amount)} has been recorded.`); }
  if(type==="inventory") {const qty=Number(fd.quantity),min=Number(fd.minimum);if(qty<0||min<0||Number(fd.cost)<0){showToast("Invalid inventory","Quantities and cost cannot be negative.","error");return;}const item={item:fd.item,category:fd.category,quantity:qty,unit:fd.unit,minimum:min,cost:Number(fd.cost),supplier:fd.supplier,status:"Normal",last:isoDate()};item.status=statusForStock(item);store.inventory.unshift(item);addTransaction(item,"In",qty,"Initial stock");showToast("Inventory item added",`${fd.item} is now tracked.`); }
  if(type==="membership") {if(fd.expiry<=fd.start){showToast("Invalid dates","Expiry must be after the start date.","error");return;}store.memberships.unshift({customer:fd.customer,plan:fd.plan,start:fd.start,expiry:fd.expiry,status:"Active",renewal:fd.expiry,price:fd.plan==="Silver"?650:fd.plan==="Gold"?1200:1800});showToast("Membership activated",`${fd.customer} was added to the ${fd.plan} plan.`);}
  saveStore();closeModal();renderPage(currentPage);updateNotificationUI(); }

function handlePageSubmit(e) { if(e.target.id!=="profileForm")return; e.preventDefault();const fd=Object.fromEntries(new FormData(e.target).entries());if(!/^\S+@\S+\.\S+$/.test(fd.email)||!/^[-+() 0-9]{7,}$/.test(fd.phone)){showToast("Invalid profile","Enter a valid email and phone number.","error");return;}store.profile={...(store.profile||{}),...fd,role:"Super Admin",preferences:(store.profile||{}).preferences||{booking:true,inventory:true,twoFactor:false}};saveStore();showToast("Profile updated","Your changes are saved on this device.");renderPage("profile"); }

function handlePageClick(e) { const target=e.target.closest("button,[data-page]");if(!target)return; if(target.dataset.page){e.preventDefault();renderPage(target.dataset.page);return;}if(target.dataset.openModal){openModal(target.dataset.openModal);return;}const action=target.dataset.action;
  if(action==="today"){calendarCursor=new Date();renderPage(currentPage==="calendar"?"calendar":"dashboard");return;} if(action==="calendar-view"){calendarView=target.dataset.view;renderPage("calendar");return;}if(action==="month-nav"){const amount=Number(target.dataset.direction)||1;if(calendarView==="Month")calendarCursor.setMonth(calendarCursor.getMonth()+amount);else calendarCursor.setDate(calendarCursor.getDate()+(calendarView==="Week"?7:1)*amount);renderPage("calendar");return;}
  if(action==="view-booking"){const b=store.bookings.find(x=>x.id===target.dataset.id);if(b)openModal("booking",b);return;}if(action==="stock-out"){openStockOut(Number(target.dataset.index));return;}if(action==="restock"){const item=store.inventory[Number(target.dataset.index)];if(item){const amount=Math.max(item.minimum,5);item.quantity+=amount;item.last=isoDate();item.status=statusForStock(item);addTransaction(item,"In",amount,"Restock");saveStore();showToast("Inventory restocked",`${amount} ${item.unit} added to ${item.item}.`);renderPage("inventory");}return;}
  if(action==="inventory-history"){const rows=store.inventoryTransactions||[];document.getElementById("modalEyebrow").textContent="Inventory transactions";document.getElementById("modalTitle").textContent="Stock history";recordForm.dataset.type="history";recordForm.innerHTML=`<div class="activity-list">${rows.map(r=>`<div class="activity-row"><span class="metric-icon ${r.direction==="Out"?"red":"green"}">${icon(r.direction==="Out"?"minus":"plus")}</span><div class="activity-content"><p>${escapeHtml(r.item)} · ${r.direction} ${r.quantity} ${escapeHtml(r.unit)}</p><span>${escapeHtml(r.reason)} · ${displayDate(r.at)}</span></div></div>`).join("")||`<div class="empty-state">No stock transactions yet.</div>`}</div><div class="form-actions"><button class="primary-button" type="button" id="modalCancel">Close</button></div>`;modalOverlay.classList.add("open");refreshIcons();return;}
  if(action==="receipt"){showReceipt(Number(target.dataset.index));return;}if(action==="export"){exportCurrentView();return;}if(action==="remove-photo"){if(store.profile){delete store.profile.photo;saveStore();renderPage("profile");}return;}if(action==="password"){showToast("Password protection","Connect a secure authentication provider before enabling password changes.","error");return;}if(target.dataset.preference){const p=store.profile||{preferences:{booking:true,inventory:true,twoFactor:false}};p.preferences=p.preferences||{};p.preferences[target.dataset.preference]=!p.preferences[target.dataset.preference];store.profile=p;saveStore();target.classList.toggle("on",p.preferences[target.dataset.preference]);showToast("Preference updated","Your notification preference was saved.");return;}
}

document.addEventListener("change", e=>{if(e.target.id!=="profilePhoto")return;const file=e.target.files[0];if(!file)return;if(!["image/jpeg","image/png","image/webp"].includes(file.type)||file.size>2*1024*1024){showToast("Invalid image","Use a PNG, JPEG, or WebP image under 2 MB.","error");e.target.value="";return;}const reader=new FileReader();reader.onload=()=>{store.profile={...(store.profile||{}),photo:reader.result,preferences:(store.profile||{}).preferences||{booking:true,inventory:true,twoFactor:false}};saveStore();renderPage("profile");showToast("Profile photo updated","Your new photo is now displayed.");};reader.readAsDataURL(file);});
document.addEventListener("DOMContentLoaded",()=>{syncDerivedData();setInterval(refreshClock,30000);});

/* Final event overrides: the root uses delegated handlers, so newly rendered controls stay functional. */
function handleRecordSubmit(e) { e.preventDefault(); const type=recordForm.dataset.type; const fd=Object.fromEntries(new FormData(recordForm).entries()); if(!validateRecordForm()) { showToast("Check required fields","Please complete required fields.","error"); return; }
  if(type==="stock-out"){const item=store.inventory[Number(recordForm.dataset.index)],qty=Number(fd.quantity);if(!item||qty<=0||qty>item.quantity||!fd.reason.trim()){showToast("Unable to record stock out",`Enter 1–${item?.quantity||0} and a reason.`,"error");return;}item.quantity-=qty;item.last=isoDate();item.status=statusForStock(item);addTransaction(item,"Out",qty,fd.reason);saveStore();closeModal();renderPage("inventory");showToast("Stock usage recorded",`${qty} ${item.unit} removed from ${item.item}.`);return;}
  if(type==="booking"){if(!/^[-+() 0-9]{7,}$/.test(fd.phone)){showToast("Invalid booking","Enter a valid phone number.","error");return;}const existing=store.bookings.find(b=>b.id===recordForm.dataset.editId),data={customer:fd.customer,phone:fd.phone,vehicle:fd.vehicle,package:fd.package,date:fd.date,time:fd.time,price:Number(fd.price),initials:initials(fd.customer)};if(existing)Object.assign(existing,data);else{store.bookings.unshift({id:`BK-${Date.now().toString().slice(-7)}`,...data,payment:"Pending",status:"Pending"});if(!store.customers.some(c=>c.name.toLowerCase()===fd.customer.toLowerCase()))store.customers.unshift({name:fd.customer,phone:fd.phone,email:"—",address:"—",membership:"—",spent:0,service:"New booking",status:"Active",joined:isoDate(),initials:initials(fd.customer)});}showToast(existing?"Booking updated":"Booking created",`${fd.customer}'s booking is synchronized.`);}
  else if(type==="customer"){if(!/^\S+@\S+\.\S+$/.test(fd.email)||!/^[-+() 0-9]{7,}$/.test(fd.phone)){showToast("Invalid customer","Use a valid email and phone number.","error");return;}if(store.customers.some(c=>c.email.toLowerCase()===fd.email.toLowerCase())){showToast("Duplicate customer","That email already exists.","error");return;}store.customers.unshift({name:fd.name,phone:fd.phone,email:fd.email,address:fd.address,membership:fd.membership||"—",spent:0,service:"No services",status:"Active",joined:isoDate(),initials:initials(fd.name)});showToast("Customer added",`${fd.name} is now in your customer list.`);}
  else if(type==="payment"){if(Number(fd.amount)<=0){showToast("Invalid payment","Amount must be greater than zero.","error");return;}store.payments.unshift({invoice:`INV-${new Date().getFullYear()}-${1000+store.payments.length}`,customer:fd.customer,date:fd.date,amount:Number(fd.amount),method:fd.method,status:"Paid",booking:fd.booking||"—"});const c=store.customers.find(x=>x.name.toLowerCase()===fd.customer.toLowerCase());if(c)c.spent=Number(c.spent||0)+Number(fd.amount);showToast("Payment recorded",`${formatMoney(fd.amount)} has been recorded.`);}
  else if(type==="inventory"){const item={item:fd.item,category:fd.category,quantity:Number(fd.quantity),unit:fd.unit,minimum:Number(fd.minimum),cost:Number(fd.cost),supplier:fd.supplier,last:isoDate()};if(item.quantity<0||item.minimum<0||item.cost<0){showToast("Invalid inventory","Values cannot be negative.","error");return;}item.status=statusForStock(item);store.inventory.unshift(item);addTransaction(item,"In",item.quantity,"Initial stock");showToast("Inventory item added",`${item.item} is now tracked.`);}
  else if(type==="membership"){if(fd.expiry<=fd.start){showToast("Invalid dates","Expiry must be after start.","error");return;}store.memberships.unshift({customer:fd.customer,plan:fd.plan,start:fd.start,expiry:fd.expiry,status:"Active",renewal:fd.expiry,price:fd.plan==="Silver"?650:fd.plan==="Gold"?1200:1800});showToast("Membership activated",`${fd.customer} was added.`);}
  saveStore();closeModal();renderPage(currentPage);updateNotificationUI(); }

function handlePageClick(e) { const t=e.target.closest("button,[data-page]");if(!t)return;if(t.dataset.page){e.preventDefault();renderPage(t.dataset.page);return;}if(t.dataset.openModal){openModal(t.dataset.openModal);return;}const a=t.dataset.action;
 if(a==="today"){calendarCursor=new Date();renderPage(currentPage==="calendar"?"calendar":"dashboard");return;}if(a==="calendar-view"){calendarView=t.dataset.view;renderPage("calendar");return;}if(a==="month-nav"){const n=Number(t.dataset.direction)||1;if(calendarView==="Month")calendarCursor.setMonth(calendarCursor.getMonth()+n);else calendarCursor.setDate(calendarCursor.getDate()+n*(calendarView==="Week"?7:1));renderPage("calendar");return;}if(a==="view-booking"){const b=store.bookings.find(x=>x.id===t.dataset.id);if(b)openModal("booking",b);return;}if(a==="stock-out"){openStockOut(Number(t.dataset.index));return;}if(a==="inventory-history"){const rows=store.inventoryTransactions||[];document.getElementById("modalEyebrow").textContent="Inventory transactions";document.getElementById("modalTitle").textContent="Stock history";recordForm.innerHTML=`<div class="activity-list">${rows.map(r=>`<div class="activity-row"><div class="activity-content"><p>${escapeHtml(r.item)} — ${r.direction} ${r.quantity} ${escapeHtml(r.unit)}</p><span>${escapeHtml(r.reason)} · ${displayDate(r.at)}</span></div></div>`).join("")||"<div class='empty-state'>No stock transactions yet.</div>"}</div><div class="form-actions"><button class="primary-button" id="modalCancel" type="button">Close</button></div>`;modalOverlay.classList.add("open");return;}if(a==="stock-out"||a==="restock")return;if(a==="restock"){const i=store.inventory[Number(t.dataset.index)];if(i){const q=Math.max(5,i.minimum);i.quantity+=q;i.last=isoDate();i.status=statusForStock(i);addTransaction(i,"In",q,"Restock");saveStore();renderPage("inventory");showToast("Inventory restocked",`${q} ${i.unit} added.`);}return;}if(a==="receipt"){showReceipt(Number(t.dataset.index));return;}if(a==="export"){exportCurrentView();return;}if(a==="remove-photo"){delete store.profile.photo;saveStore();renderPage("profile");return;}if(t.dataset.preference){store.profile=store.profile||{preferences:{}};store.profile.preferences[t.dataset.preference]=!store.profile.preferences[t.dataset.preference];saveStore();t.classList.toggle("on",store.profile.preferences[t.dataset.preference]);return;} }

function customersPage() {
  const rows = filtered(store.customers,["name","phone","email","address","membership"]);
  return `<section class="page-transition">${pageHeader("Customers", "A complete picture of every client, their preferences, and service history.", `<button class="outline-button" type="button" data-action="export">${icon("download")} Export</button><button class="primary-button" type="button" data-open-modal="customer">${icon("user-round-plus")} Add Customer</button>`)}<div class="customer-summary"><section class="panel summary-card"><h3>Customer Overview</h3><div class="summary-stats"><div class="summary-stat"><small>Total Customers</small><strong>${store.customers.length + 42}</strong></div><div class="summary-stat"><small>New this month</small><strong>4</strong></div><div class="summary-stat"><small>Repeat customers</small><strong>18</strong></div></div></section><section class="panel summary-card"><h3>Customer Notes</h3><div class="note-box">John Mensah prefers fragrance-free interior products. His next Gold Plan service is scheduled for 12 July.</div></section></div><div class="toolbar" style="margin-top:14px"><label class="local-search">${icon("search")}<input id="localSearch" value="${escapeHtml(localFilter)}" placeholder="Search customers..." /></label><div class="toolbar-actions"><button class="filter-button" type="button" data-action="filter-info">${icon("list-filter")} Filter</button></div></div><section class="panel data-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Phone Number</th><th>Email</th><th>Address</th><th>Membership</th><th>Total Spent</th><th>Last Service</th><th>Status</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><div class="customer-cell">${tinyAvatar(c.name,c.initials)}<strong>${escapeHtml(c.name)}</strong></div></td><td>${c.phone}</td><td>${escapeHtml(c.email)}</td><td>${escapeHtml(c.address)}</td><td>${c.membership === "—" ? "—" : statusBadge(c.membership === "Gold" ? "Active" : c.membership)}</td><td>${formatMoney(c.spent)}</td><td>${c.service}</td><td>${statusBadge(c.status)}</td><td><button class="row-action" data-action="view-customer" data-name="${escapeHtml(c.name)}" title="View customer">${icon("arrow-up-right")}</button></td></tr>`).join("") || `<tr><td colspan="9"><div class="empty-state">No customers found.</div></td></tr>`}</tbody></table></div><div class="pagination"><span>Showing ${rows.length} customers</span><div class="pagination-buttons"><button class="page-dot active">1</button><button class="page-dot">2</button></div></div></section></section>`;
}

function inventoryPage() {
  const rows = filtered(store.inventory,["item","category","supplier","status"]);
  return `<section class="page-transition">${pageHeader("Inventory", "Keep the mobile detailing team supplied and never miss a low-stock item.", `<button class="outline-button" type="button" data-action="inventory-history">${icon("history")} History</button><button class="primary-button" type="button" data-open-modal="inventory">${icon("plus")} Add Item</button>`)}<div class="inventory-alerts"><section class="panel alert-summary"><span class="metric-icon red">${icon("triangle-alert")}</span><div><h3>3 critical / low-stock alerts</h3><p>Restock these supplies before tomorrow’s bookings.</p></div></section><section class="panel alert-summary"><span class="metric-icon gold">${icon("package-check")}</span><div><h3>85% stock health</h3><p>17 of 20 tracked items are at healthy levels.</p></div></section><section class="panel alert-summary"><span class="metric-icon teal">${icon("truck")}</span><div><h3>Next supplier delivery</h3><p>AutoChem Ghana · 03 July 2024</p></div></section></div><div class="toolbar"><label class="local-search">${icon("search")}<input id="localSearch" value="${escapeHtml(localFilter)}" placeholder="Search inventory..." /></label><div class="toolbar-actions"><button class="filter-button" type="button" data-action="filter-info">${icon("list-filter")} Filter</button><button class="filter-button" type="button" data-action="export">${icon("download")} Export</button></div></div><section class="panel data-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Item Name</th><th>Category</th><th>Quantity</th><th>Minimum Stock</th><th>Unit Cost</th><th>Supplier</th><th>Last Restocked</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.map((i,index)=>`<tr><td><strong>${escapeHtml(i.item)}</strong></td><td>${escapeHtml(i.category)}</td><td>${i.quantity} ${escapeHtml(i.unit)}</td><td>${i.minimum} ${escapeHtml(i.unit)}</td><td>${formatMoney(i.cost)}</td><td>${escapeHtml(i.supplier)}</td><td>${i.last}</td><td>${statusBadge(i.status)}</td><td><div class="row-actions"><button class="row-action" data-action="restock" data-index="${index}" title="Restock">${icon("package-plus")}</button><button class="row-action" data-action="delete-inventory" data-index="${index}" title="Delete item">${icon("trash-2")}</button></div></td></tr>`).join("") || `<tr><td colspan="9"><div class="empty-state">No inventory items found.</div></td></tr>`}</tbody></table></div></section></section>`;
}

function membershipsPage() {
  const plans = [{name:"Silver Plan", price:650, subscribers:8, revenue:5200, benefits:["2 services every month","Priority booking slots","Exterior + interior refresh"]},{name:"Gold Plan",price:1200,subscribers:11,revenue:13200,benefits:["4 services every month","Preferred service windows","Full maintenance detail"]},{name:"Platinum Plan",price:1800,subscribers:4,revenue:7200,benefits:["Weekly maintenance","Premium protection checks","Highest booking priority"]}];
  const rows=filtered(store.memberships,["customer","plan","status"]);
  return `<section class="page-transition">${pageHeader("Memberships", "Manage recurring care plans and grow predictable revenue.", `<button class="primary-button" type="button" data-open-modal="membership">${icon("plus")} Add Membership</button>`)}<div class="membership-grid">${plans.map((p,i)=>`<section class="panel membership-card"><p class="eyebrow">${i===1?"Most popular":"Monthly care"}</p><h3>${p.name}</h3><div class="membership-price">${formatMoney(p.price)} <small>/ month</small></div><p>${p.subscribers} active subscribers · ${formatMoney(p.revenue)} monthly revenue</p><div class="benefits">${p.benefits.map(x=>`<span>${icon("check")} ${x}</span>`).join("")}</div><button class="outline-button small-button" type="button" data-action="plan-details">View plan</button></section>`).join("")}</div><div class="toolbar"><label class="local-search">${icon("search")}<input id="localSearch" value="${escapeHtml(localFilter)}" placeholder="Search members..." /></label><button class="filter-button" type="button" data-action="filter-info">${icon("list-filter")} Filter</button></div><section class="panel data-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Customer Name</th><th>Plan</th><th>Start Date</th><th>Expiry Date</th><th>Status</th><th>Renewal Date</th><th>Monthly Price</th><th>Actions</th></tr></thead><tbody>${rows.map((m,index)=>`<tr><td><div class="customer-cell">${tinyAvatar(m.customer)}<strong>${escapeHtml(m.customer)}</strong></div></td><td>${escapeHtml(m.plan)}</td><td>${m.start}</td><td>${m.expiry}</td><td>${statusBadge(m.status)}</td><td>${m.renewal}</td><td>${formatMoney(m.price)}</td><td><div class="row-actions"><button class="row-action" data-action="renew-membership" data-index="${index}" title="Renew">${icon("refresh-cw")}</button><button class="row-action" data-action="membership-details" title="View details">${icon("eye")}</button></div></td></tr>`).join("")}</tbody></table></div></section></section>`;
}

function paymentsPage() {
  const rows=filtered(store.payments,["invoice","customer","method","status","booking"]);
  return `<section class="page-transition">${pageHeader("Payments", "Record transactions, issue receipts, and follow outstanding invoices.", `<button class="outline-button" type="button" data-action="export">${icon("download")} Export</button><button class="primary-button" type="button" data-open-modal="payment">${icon("plus")} Record Payment</button>`)}<div class="kpi-grid" style="grid-template-columns:repeat(4,minmax(0,1fr));margin-bottom:14px">${metricCard("circle-dollar-sign","gold","Today’s Revenue",formatMoney(2450),"+12.5%","vs yesterday")}${metricCard("chart-no-axes-combined","green","Weekly Revenue",formatMoney(15650),"+8.2%","vs last week")}${metricCard("calendar-range","blue","Monthly Revenue",formatMoney(68750),"+15.7%","vs last month")}${metricCard("clock-3","orange","Pending Payments",formatMoney(2050),"3 invoices","need follow-up")}</div><div class="toolbar"><label class="local-search">${icon("search")}<input id="localSearch" value="${escapeHtml(localFilter)}" placeholder="Search invoices, customer..." /></label><div class="toolbar-actions"><button class="filter-button" type="button" data-action="filter-info">${icon("list-filter")} Filter</button></div></div><section class="panel data-panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Invoice Number</th><th>Customer</th><th>Date</th><th>Amount</th><th>Method</th><th>Status</th><th>Booking</th><th>Actions</th></tr></thead><tbody>${rows.map((p,index)=>`<tr><td><strong>${p.invoice}</strong></td><td>${escapeHtml(p.customer)}</td><td>${p.date}</td><td>${formatMoney(p.amount)}</td><td>${p.method}</td><td>${statusBadge(p.status)}</td><td>${p.booking}</td><td><div class="row-actions"><button class="row-action" data-action="receipt" data-index="${index}" title="Receipt">${icon("receipt-text")}</button><button class="row-action" data-action="payment-details" title="View payment">${icon("eye")}</button></div></td></tr>`).join("")}</tbody></table></div></section></section>`;
}

function reportsPage() { return `<section class="page-transition">${pageHeader("Reports", "Track performance, identify trends, and make better decisions every day.", `<button class="primary-button" type="button" data-action="generate-report">${icon("file-down")} Generate Report</button>`)}<div class="reports-grid"><section class="panel chart-panel"><div class="panel-header"><h2>Revenue &amp; Profit</h2><button class="chart-select" type="button" data-action="change-chart">Last 30 days ${icon("chevron-down")}</button></div>${revenueChart()}</section><aside class="report-metrics"><section class="panel report-metric"><div><small>Total Revenue</small><strong>${formatMoney(68750)}</strong></div><b>+15.7%</b></section><section class="panel report-metric"><div><small>Operating Expenses</small><strong>${formatMoney(18520)}</strong></div><b>+4.1%</b></section><section class="panel report-metric"><div><small>Net Profit</small><strong>${formatMoney(50230)}</strong></div><b>+21.3%</b></section></aside></div><section class="panel summary-card" style="margin-top:14px"><div class="panel-header"><h2>Export center</h2><span class="subtext">Create a share-ready version of the selected report.</span></div><div class="export-list"><div class="export-option"><span>${icon("file-text")} Daily Operations Report</span><button type="button" data-action="export">Download PDF</button></div><div class="export-option"><span>${icon("sheet")} Monthly Revenue Report</span><button type="button" data-action="export">Export CSV</button></div><div class="export-option"><span>${icon("users-round")} Customer Retention Report</span><button type="button" data-action="export">Print</button></div><div class="export-option"><span>${icon("boxes")} Inventory Usage Report</span><button type="button" data-action="export">Export Excel</button></div></div></section></section>`; }

function profilePage() { return `<section class="page-transition">${pageHeader("Profile & Settings", "Manage your account, security, and Command Center preferences.")}<div class="profile-layout"><aside class="panel profile-card"><span class="avatar profile-avatar avatar-main">AM</span><h2>Admin Mensah</h2><p>admin@driveandshine.com</p><div class="profile-badges">${statusBadge("Active")}<span class="status confirmed">Super Admin</span></div><div class="form-section" style="text-align:left"><h3>Account summary</h3><div class="setting-row"><div><b>Member since</b><span>12 March 2023</span></div></div><div class="setting-row"><div><b>Last sign in</b><span>Today at 08:12 AM</span></div></div></div></aside><section class="panel profile-form"><h2>Personal information</h2><form id="profileForm"><div class="form-grid"><label class="form-field"><span>Full Name</span><input name="fullName" value="Admin Mensah" required /></label><label class="form-field"><span>Email Address</span><input name="email" type="email" value="admin@driveandshine.com" required /></label><label class="form-field"><span>Phone Number</span><input name="phone" value="024 000 0000" required /></label><label class="form-field"><span>Role</span><input value="Super Admin" disabled /></label></div><div class="form-section"><h3>Preferences</h3><div class="setting-row"><div><b>Booking notifications</b><span>Receive notifications for new bookings and updates.</span></div><button class="toggle on" type="button" aria-label="Toggle booking notifications"></button></div><div class="setting-row"><div><b>Inventory alerts</b><span>Notify when an item reaches minimum stock.</span></div><button class="toggle on" type="button" aria-label="Toggle inventory alerts"></button></div><div class="setting-row"><div><b>Two-factor authentication</b><span>Add a second verification step when signing in.</span></div><button class="toggle" type="button" aria-label="Toggle two factor authentication"></button></div></div><div class="form-actions"><button class="outline-button" type="button" data-action="password">Change Password</button><button class="primary-button" type="submit">${icon("save")} Save Changes</button></div></form></section></div></section>`; }

function notificationsPage() { const typeMap={Bookings:"booking",Payments:"payment",Inventory:"inventory",Memberships:"membership",System:"system"}; let rows=filtered(store.notifications,["title","text","type"]); if(notificationFilter!=="All") rows=rows.filter(n=>n.type===typeMap[notificationFilter]); return `<section class="page-transition">${pageHeader("Notifications", "Stay on top of bookings, payments, memberships, inventory, and system activity.", `<button class="outline-button" type="button" data-action="mark-all-read">${icon("check-check")} Mark all as read</button>`)}<div class="tabs">${["All","Bookings","Payments","Inventory","Memberships","System"].map(name=>`<button class="tab ${notificationFilter===name?"active":""}" type="button" data-action="notification-filter">${name}</button>`).join("")}</div><div class="notification-list">${rows.map(n=>`<article class="panel notification-card ${n.read?"":"unread"}"><span class="metric-icon ${n.type === "inventory" ? "red" : n.type === "payment" ? "green" : n.type === "membership" ? "purple" : "gold"}">${icon(n.icon)}</span><div><h3>${escapeHtml(n.title)}</h3><p>${escapeHtml(n.text)}</p></div><time>${n.time}</time><button class="row-action" type="button" data-action="delete-notification" data-id="${n.id}" title="Delete notification">${icon("trash-2")}</button></article>`).join("") || `<section class="panel empty-state">No ${notificationFilter.toLowerCase()} notifications match this search.</section>`}</div></section>`; }

function renderPage(page = currentPage) {
  currentPage = page;
  localFilter = "";
  const pages = {dashboard: dashboardPage, bookings: bookingsPage, calendar: calendarPage, customers: customersPage, inventory: inventoryPage, memberships: membershipsPage, payments: paymentsPage, reports: reportsPage, profile: profilePage, notifications: notificationsPage};
  pageRoot.innerHTML = (pages[page] || dashboardPage)();
  document.querySelectorAll(".nav-item").forEach(a => a.classList.toggle("active", a.dataset.page === page));
  document.querySelectorAll("[data-page]").forEach(el => { if (el.tagName === "A") el.setAttribute("aria-current", el.dataset.page === page ? "page" : "false"); });
  window.history.replaceState(null, "", `#${page}`);
  refreshIcons();
  pageRoot.focus({preventScroll:true});
}

function updateNotificationUI() {
  const count = unreadCount();
  document.getElementById("notificationBadge").textContent = count;
  document.getElementById("sideNotificationCount").textContent = count;
  document.getElementById("popoverNotifications").innerHTML = store.notifications.slice(0,4).map(n => `<button class="popover-item" data-page="notifications" type="button">${icon(n.icon)}<span><strong>${escapeHtml(n.title)}</strong><span>${escapeHtml(n.text)}</span></span></button>`).join("");
  document.querySelectorAll("#popoverNotifications [data-page]").forEach(button => button.addEventListener("click", () => {
    document.getElementById("notificationPopover").classList.remove("open");
    renderPage(button.dataset.page);
  }));
  refreshIcons();
}

function showToast(title, message, type = "success") { const toast=document.createElement("div"); toast.className=`toast ${type === "error" ? "error" : ""}`; toast.innerHTML=`${icon(type === "error" ? "circle-alert" : "circle-check-big")}<div><strong>${escapeHtml(title)}</strong><span>${escapeHtml(message)}</span></div>`; toastStack.appendChild(toast); refreshIcons(); setTimeout(()=>toast.remove(),4200); }
function exportCurrentView() {
  const exports = {
    bookings: store.bookings,
    customers: store.customers,
    inventory: store.inventory,
    memberships: store.memberships,
    payments: store.payments,
    notifications: store.notifications,
    reports: [{ report: "Monthly performance", revenue: 68750, expenses: 18520, profit: 50230 }]
  };
  const rows = exports[currentPage] || store.bookings;
  const headers = [...new Set(rows.flatMap((row) => Object.keys(row)))];
  const csv = [headers.join(","), ...rows.map((row) => headers.map((key) => `"${String(row[key] ?? "").replaceAll('"', '""')}"`).join(","))].join("\n");
  const link = document.createElement("a");
  link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
  link.download = `drive-shine-${currentPage}-${new Date().toISOString().slice(0, 10)}.csv`;
  document.body.appendChild(link);
  link.click();
  link.remove();
  URL.revokeObjectURL(link.href);
  showToast("Export downloaded", `Your ${currentPage} CSV has been created.`);
}
function closeModal() { modalOverlay.classList.remove("open"); modalOverlay.setAttribute("aria-hidden","true"); recordForm.innerHTML=""; }
function field(label, name, type="text", placeholder="", options="", required=true) { const input = type === "select" ? `<select name="${name}" ${required?"required":""}><option value="">Select ${label.toLowerCase()}</option>${options.split("|").map(o=>`<option>${o}</option>`).join("")}</select>` : type === "textarea" ? `<textarea name="${name}" placeholder="${placeholder}" ${required?"required":""}></textarea>` : `<input name="${name}" type="${type}" placeholder="${placeholder}" ${required?"required":""} />`; return `<label class="form-field"><span>${label}</span>${input}<small class="form-error"></small></label>`; }
function openModal(type, prefill = {}) {
  const configs = {
    booking: { eyebrow:"Appointments", title:"Create booking", fields:[field("Customer Name","customer","text","e.g. John Mensah"),field("Phone Number","phone","tel","024 000 0000"),field("Vehicle","vehicle","text","e.g. Toyota Prado"),field("Service Package","package","select","","Premium Detail|Full Service Wash|Interior Cleaning|Engine Bay Clean|Gold Membership|Platinum Membership"),field("Service Date","date","date"),field("Service Time","time","select","","08:00 AM|09:00 AM|10:30 AM|12:00 PM|02:30 PM|04:00 PM"),field("Price (GHS)","price","number","0"),field("Notes","notes","textarea","Special requests or booking notes", "", false)] },
    customer: { eyebrow:"Customers", title:"Add customer", fields:[field("Full Name","name","text","Customer name"),field("Phone Number","phone","tel","024 000 0000"),field("Email Address","email","email","name@email.com"),field("Address","address","text","Area, city"),field("Membership Plan","membership","select","","None|Silver|Gold|Platinum",false)] },
    payment: { eyebrow:"Payments", title:"Record payment", fields:[field("Customer Name","customer","text","Customer name"),field("Amount (GHS)","amount","number","0"),field("Payment Method","method","select","","Cash|MTN Mobile Money|Telecel Cash|AirtelTigo Money|Bank Transfer|Card"),field("Payment Date","date","date"),field("Booking ID","booking","text","BK-240630", "", false)] },
    inventory: { eyebrow:"Inventory", title:"Add inventory item", fields:[field("Item Name","item","text","e.g. Wheel Cleaner"),field("Category","category","select","","Chemicals|Tools|Microfiber Towels|Machines|Consumables"),field("Quantity","quantity","number","0"),field("Unit","unit","select","","bottles|pieces|sets|units|boxes"),field("Minimum Stock","minimum","number","0"),field("Unit Cost (GHS)","cost","number","0"),field("Supplier","supplier","text","Supplier name")] },
    membership: { eyebrow:"Memberships", title:"Add membership", fields:[field("Customer Name","customer","text","Customer name"),field("Membership Plan","plan","select","","Silver|Gold|Platinum"),field("Start Date","start","date"),field("Expiry Date","expiry","date")] },
    plan: { eyebrow:"Subscription", title:"Manage Gold Plan", fields:[`<div class="note-box">Your Command Center is on the Gold Plan. You have full access to scheduling, customer management, reporting, and 5 team seats.</div>`] }
  };
  const cfg=configs[type]; if(!cfg) return;
  document.getElementById("modalEyebrow").textContent=cfg.eyebrow; document.getElementById("modalTitle").textContent=cfg.title;
  recordForm.dataset.type=type; recordForm.innerHTML=`<div class="form-grid">${cfg.fields.join("")}</div><div class="form-actions"><button class="outline-button" type="button" id="modalCancel">Cancel</button><button class="primary-button" type="submit">${icon(type==="plan"?"credit-card":"save")} ${type==="plan"?"Manage subscription":"Save record"}</button></div>`;
  Object.entries(prefill).forEach(([key,value])=>{ const el=recordForm.elements[key]; if(el) el.value=value; });
  if (type === "booking" && prefill.id) {
    recordForm.dataset.editId = prefill.id;
    document.getElementById("modalEyebrow").textContent = "Booking details";
    document.getElementById("modalTitle").textContent = `Edit ${prefill.id}`;
    recordForm.querySelector("button[type='submit']").innerHTML = `${icon("save")} Save changes`;
  } else {
    delete recordForm.dataset.editId;
  }
  modalOverlay.classList.add("open"); modalOverlay.setAttribute("aria-hidden","false"); refreshIcons(); setTimeout(()=>recordForm.querySelector("input,select,textarea")?.focus(),80);
}
function validateRecordForm() { let ok=true; recordForm.querySelectorAll("[required]").forEach(el=>{ const error=el.parentElement.querySelector(".form-error"); if(!el.value.trim()) { ok=false; el.style.borderColor="#fa6363"; error.textContent="This field is required."; } else { el.style.borderColor=""; error.textContent=""; } }); return ok; }
function handleRecordSubmit(e) { e.preventDefault(); const type=recordForm.dataset.type; if(type==="plan") { closeModal(); showToast("Plan details", "Subscription controls are ready for your billing portal."); return; } if(!validateRecordForm()) { showToast("Check required fields", "Please complete the highlighted fields.","error"); return; } const fd=Object.fromEntries(new FormData(recordForm).entries()); if(type === "booking") { const existing=store.bookings.find(item=>item.id===recordForm.dataset.editId); if(existing) { Object.assign(existing,{customer:fd.customer,phone:fd.phone,vehicle:fd.vehicle,package:fd.package,date:fd.date,time:fd.time,price:Number(fd.price),initials:initials(fd.customer)}); showToast("Booking updated", `${fd.customer}'s booking details have been saved.`); } else { const id=`BK-${String(Date.now()).slice(-6)}`; store.bookings.unshift({id, customer:fd.customer, phone:fd.phone, vehicle:fd.vehicle, package:fd.package, date:fd.date, time:fd.time, price:Number(fd.price), payment:"Pending",status:"Pending",initials:initials(fd.customer)}); if(!store.customers.some(c=>c.name.toLowerCase()===fd.customer.toLowerCase())) store.customers.unshift({name:fd.customer,phone:fd.phone,email:"—",address:"—",membership:"—",spent:0,service:"New",status:"Active",joined:"30 Jun 2024",initials:initials(fd.customer)}); showToast("Booking created", `${fd.customer}'s booking has been added to the schedule.`); } }
  if(type === "customer") { store.customers.unshift({name:fd.name,phone:fd.phone,email:fd.email,address:fd.address,membership:fd.membership||"—",spent:0,service:"No services",status:"Active",joined:"30 Jun 2024",initials:initials(fd.name)}); showToast("Customer added", `${fd.name} is now in your customer list.`); }
  if(type === "payment") { store.payments.unshift({invoice:`INV-2024-${1030+store.payments.length}`,customer:fd.customer,date:fd.date?new Date(fd.date).toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"}):"30 Jun 2024",amount:Number(fd.amount),method:fd.method,status:"Paid",booking:fd.booking||"—"}); showToast("Payment recorded", `${formatMoney(fd.amount)} has been recorded as paid.`); }
  if(type === "inventory") { const qty=Number(fd.quantity), min=Number(fd.minimum); store.inventory.unshift({item:fd.item,category:fd.category,quantity:qty,unit:fd.unit,minimum:min,cost:Number(fd.cost),supplier:fd.supplier,status:qty<=min/2?"Critical":qty<=min?"Low":"Normal",last:"30 Jun 2024"}); showToast("Inventory item added", `${fd.item} is now being tracked.`); }
  if(type === "membership") { store.memberships.unshift({customer:fd.customer,plan:fd.plan,start:fd.start,expiry:fd.expiry,status:"Active",renewal:fd.expiry,price:fd.plan==="Silver"?650:fd.plan==="Gold"?1200:1800}); showToast("Membership activated", `${fd.customer} was added to the ${fd.plan} Plan.`); }
  saveStore(); closeModal(); renderPage(currentPage); updateNotificationUI(); }

function attachEvents() {
  document.getElementById("sidebarToggle").addEventListener("click",()=> { if(window.innerWidth<=680) appShell.classList.toggle("sidebar-open"); else appShell.classList.toggle("sidebar-collapsed"); });
  document.querySelectorAll("[data-page]").forEach(el=>el.addEventListener("click",e=>{e.preventDefault(); if(el.dataset.page) { document.getElementById("profileMenu").classList.remove("open"); document.getElementById("notificationPopover").classList.remove("open"); if(window.innerWidth<=680) appShell.classList.remove("sidebar-open"); renderPage(el.dataset.page); }}));
  document.getElementById("notificationBell").addEventListener("click",()=> { document.getElementById("notificationPopover").classList.toggle("open"); document.getElementById("profileMenu").classList.remove("open"); });
  document.getElementById("profileTrigger").addEventListener("click",()=> { document.getElementById("profileMenu").classList.toggle("open"); document.getElementById("notificationPopover").classList.remove("open"); });
  document.getElementById("markAllRead").addEventListener("click",markAllRead);
  document.getElementById("lightMode").addEventListener("click",()=>setTheme("light")); document.getElementById("darkMode").addEventListener("click",()=>setTheme("dark"));
  document.getElementById("logoutButton").addEventListener("click",()=>showToast("Sign-out confirmation", "Your secure sign-out workflow is ready."));
  document.querySelectorAll(".sidebar [data-open-modal]").forEach(button => button.addEventListener("click", () => openModal(button.dataset.openModal)));
  document.getElementById("globalSearch").addEventListener("focus",openPalette); document.getElementById("globalSearch").addEventListener("input",e=>{openPalette(); document.getElementById("paletteSearch").value=e.target.value; renderCommandResults(e.target.value);}); document.getElementById("paletteSearch").addEventListener("input",e=>renderCommandResults(e.target.value));
  document.addEventListener("keydown",e=>{ if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();openPalette();} if(e.key==="Escape"){closePalette();closeModal();} });
  document.getElementById("closeModal").addEventListener("click",closeModal); modalOverlay.addEventListener("click",e=>{if(e.target===modalOverlay)closeModal();}); recordForm.addEventListener("submit",handleRecordSubmit); recordForm.addEventListener("click",e=>{ if(e.target.closest("#modalCancel")) closeModal(); });
  pageRoot.addEventListener("click",handlePageClick); pageRoot.addEventListener("input",handlePageInput); pageRoot.addEventListener("submit",handlePageSubmit);
  document.addEventListener("click",e=>{if(!e.target.closest(".notification-wrap"))document.getElementById("notificationPopover").classList.remove("open"); if(!e.target.closest(".profile-menu-wrap"))document.getElementById("profileMenu").classList.remove("open");});
}
function handlePageInput(e) { if(e.target.id==="localSearch") { localFilter=e.target.value; const start=e.target.selectionStart; const val=e.target.value; const page=currentPage; const pages={bookings:bookingsPage,customers:customersPage,inventory:inventoryPage,memberships:membershipsPage,payments:paymentsPage,notifications:notificationsPage}; if(pages[page]) { pageRoot.innerHTML=`<section class="page-transition">${pages[page]().replace(/^<section class="page-transition">|<\/section>$/g,"")}</section>`; refreshIcons(); const input=document.getElementById("localSearch"); if(input){input.focus();input.setSelectionRange(start,start);} } } }
function handlePageSubmit(e) { if(e.target.id==="profileForm") { e.preventDefault(); showToast("Profile updated", "Your account preferences have been saved."); } }
function handlePageClick(e) {
  const target=e.target.closest("button,[data-page]"); if(!target) return;
  if(target.dataset.page){e.preventDefault();renderPage(target.dataset.page);return;}
  const action=target.dataset.action;
  if(target.dataset.openModal){openModal(target.dataset.openModal);return;}
  if(target.id==="modalCancel"){closeModal();return;}
  if(target.classList.contains("page-dot")){ showToast("Page selected", `You are viewing page ${target.textContent.trim() === "›" ? "2" : target.textContent.trim()} of the current records.`); return; }
  if(target.dataset.bookingTab){bookingFilter=target.dataset.bookingTab; localFilter=""; renderPage("bookings");return;}
  if(action === "view-booking") { const b=store.bookings.find(x=>x.id===target.dataset.id); openModal("booking",b||{}); document.getElementById("modalTitle").textContent=`Booking ${target.dataset.id}`; return; }
  if(action === "delete-booking") { if(confirm("Delete this booking?")){store.bookings=store.bookings.filter(x=>x.id!==target.dataset.id);saveStore();showToast("Booking deleted","The booking was removed from your schedule.");renderPage("bookings");} return; }
  if(action === "delete-inventory") { const item=store.inventory[Number(target.dataset.index)]; if(item&&confirm(`Delete ${item.item}?`)){store.inventory.splice(Number(target.dataset.index),1);saveStore();showToast("Item deleted","Inventory has been updated.");renderPage("inventory");} return; }
  if(action === "restock") { const item=store.inventory[Number(target.dataset.index)]; if(item){item.quantity+=Math.max(5,item.minimum);item.status="Normal";item.last="30 Jun 2024";saveStore();showToast("Inventory restocked",`${item.item} now has ${item.quantity} ${item.unit}.`);renderPage("inventory");} return; }
  if(action === "renew-membership") { const m=store.memberships[Number(target.dataset.index)]; if(m){m.status="Active";m.renewal="30 Jul 2024";saveStore();showToast("Membership renewed",`${m.customer}'s ${m.plan} membership is active.`);renderPage("memberships");} return; }
  if(action === "delete-notification") { store.notifications=store.notifications.filter(n=>n.id!==Number(target.dataset.id));saveStore();updateNotificationUI();renderPage("notifications");showToast("Notification removed","It was removed from your activity feed."); return; }
  if(action === "mark-all-read"){markAllRead();return;}
  if(action === "export"){exportCurrentView();return;}
  if(action === "notification-filter"){notificationFilter=target.textContent.trim(); localFilter=""; renderPage("notifications");return;}
  if(["filter-info","columns","inventory-history","plan-details","membership-details","payment-details","receipt","calendar-event","calendar-view","month-nav","change-chart","choose-date","generate-report","password","view-customer","notification-filter"].includes(action)) { const labels={"filter-info":"Filters","columns":"Column controls","inventory-history":"Inventory history","plan-details":"Plan details","membership-details":"Membership details","payment-details":"Payment details","receipt":"Receipt generated","calendar-event":"Booking details","calendar-view":"Calendar view","month-nav":"Calendar","change-chart":"Chart period","choose-date":"Date picker","generate-report":"Report generated","password":"Password settings","view-customer":"Customer profile","notification-filter":"Notifications"}; showToast(labels[action], action==="generate-report"?"Your selected report has been generated.":"The selected management action is ready."); return; }
  if(target.classList.contains("toggle")){target.classList.toggle("on");showToast("Preference updated",target.classList.contains("on")?"This setting is now enabled.":"This setting is now disabled.");}
}
function markAllRead(){store.notifications.forEach(n=>n.read=true);saveStore();updateNotificationUI();if(currentPage==="notifications")renderPage("notifications");showToast("All caught up","All notifications have been marked as read.");}
function setTheme(theme){ document.body.classList.toggle("light-theme",theme==="light");document.getElementById("lightMode").classList.toggle("active",theme==="light");document.getElementById("darkMode").classList.toggle("active",theme!=="light");localStorage.setItem("ds-theme",theme); }
function openPalette(){document.getElementById("commandPalette").classList.add("open");document.getElementById("commandPalette").setAttribute("aria-hidden","false");const q=document.getElementById("globalSearch").value;document.getElementById("paletteSearch").value=q;renderCommandResults(q);setTimeout(()=>document.getElementById("paletteSearch").focus(),40);}
function closePalette(){document.getElementById("commandPalette").classList.remove("open");document.getElementById("commandPalette").setAttribute("aria-hidden","true");document.getElementById("globalSearch").value="";}
function renderCommandResults(query="") { const q=query.toLowerCase(); const pages=[ ["dashboard","layout-dashboard","Dashboard"],["bookings","calendar-check-2","Bookings"],["calendar","calendar-days","Calendar"],["customers","users-round","Customers"],["inventory","boxes","Inventory"],["memberships","shield-check","Memberships"],["payments","credit-card","Payments"],["reports","chart-no-axes-combined","Reports"],["profile","contact-round","Profile"],["notifications","bell-ring","Notifications"]]; const items=pages.filter(x=>x[2].toLowerCase().includes(q)); const customerHits=store.customers.filter(c=>c.name.toLowerCase().includes(q)).slice(0,4); document.getElementById("commandResults").innerHTML=`<div class="command-label">Navigate</div>${items.map(x=>`<button class="command-result" type="button" data-command-page="${x[0]}">${icon(x[1])}<span>${x[2]}</span><small>Open</small></button>`).join("") || `<div class="command-result"><span>No pages found</span></div>`}${customerHits.length?`<div class="command-label">Customers</div>${customerHits.map(c=>`<button class="command-result" type="button" data-command-page="customers">${icon("user-round")}<span>${escapeHtml(c.name)}</span><small>${escapeHtml(c.phone)}</small></button>`).join("")}`:""}`; document.querySelectorAll("[data-command-page]").forEach(b=>b.addEventListener("click",()=>{closePalette();renderPage(b.dataset.commandPage);}));refreshIcons(); }

document.getElementById("commandPalette").addEventListener("click",e=>{if(e.target.id==="commandPalette")closePalette();});
document.addEventListener("DOMContentLoaded",()=>{setTheme(localStorage.getItem("ds-theme")||"dark");attachEvents();updateNotificationUI();const initial=location.hash.slice(1);renderPage(["dashboard","bookings","calendar","customers","inventory","memberships","payments","reports","profile","notifications"].includes(initial)?initial:"dashboard");});

/* Functional data layer enhancements */
const APP_VERSION = "drive-shine-command-center-v2";
let calendarCursor = new Date();
let calendarView = "Month";
let tablePage = 1;
let customerFilters = { service:"", location:"", status:"", query:"" };

function isoDate(d = new Date()) { const z = new Date(d); z.setMinutes(z.getMinutes() - z.getTimezoneOffset()); return z.toISOString().slice(0,10); }
function displayDate(value) { if (!value) return "—"; const d = /^\d{4}-\d{2}-\d{2}$/.test(value) ? new Date(`${value}T12:00:00`) : new Date(value); return Number.isNaN(d) ? value : d.toLocaleDateString("en-GB", { day:"2-digit", month:"short", year:"numeric" }); }
function statusForStock(item) { return item.quantity <= item.minimum / 2 ? "Critical" : item.quantity <= item.minimum ? "Low" : "Normal"; }
function bookingDate(b) { return b.date && /^\d{4}-\d{2}-\d{2}$/.test(b.date) ? b.date : ""; }
function paidBookings(rangeStart, rangeEnd) { return store.payments.filter(p => p.status === "Paid").filter(p => { const d = p.date && /^\d{4}-\d{2}-\d{2}$/.test(p.date) ? p.date : ""; return d && d >= rangeStart && d <= rangeEnd; }); }
function addTransaction(item, direction, quantity, reason) { store.inventoryTransactions = store.inventoryTransactions || []; store.inventoryTransactions.unshift({ id:`IT-${Date.now().toString().slice(-7)}`, item:item.item, direction, quantity, unit:item.unit, reason, at:new Date().toISOString(), remaining:item.quantity }); }
function syncDerivedData() {
  store.inventory.forEach(i => i.status = statusForStock(i));
  store.memberships.forEach(m => { const expiry = m.expiry && /^\d{4}-/.test(m.expiry) ? m.expiry : ""; if (expiry) { const days = Math.ceil((new Date(`${expiry}T12:00:00`) - new Date()) / 86400000); m.status = days < 0 ? "Expired" : days <= 14 ? "Expiring" : "Active"; } });
}
function liveDateControl() { return `<button class="date-button" type="button" data-action="today">${icon("calendar-days")} <span id="liveDate">${new Date().toLocaleString("en-GB",{weekday:"long",day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"})}</span></button>`; }
function refreshClock() { const el = document.getElementById("liveDate"); if (el) el.textContent = new Date().toLocaleString("en-GB", {weekday:"long",day:"numeric",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"}); }

function dashboardPage() {
  syncDerivedData(); const today=isoDate(), week=new Date(); week.setDate(week.getDate()-6); const weekStart=isoDate(week); const monthStart=`${today.slice(0,7)}-01`;
  const sum = a => a.reduce((n,x)=>n+Number(x.amount || x.price || 0),0);
  const todays=paidBookings(today,today), weekly=paidBookings(weekStart,today), monthly=paidBookings(monthStart,today);
  const todayBookings=store.bookings.filter(b=>bookingDate(b)===today), completed=store.bookings.filter(b=>b.status==="Completed"), low=store.inventory.filter(i=>i.status!=="Normal");
  const metrics=[["circle-dollar-sign","gold","Today’s Revenue",formatMoney(sum(todays)),`${todays.length} payments`,`recorded today`],["chart-no-axes-combined","gold","Weekly Revenue",formatMoney(sum(weekly)),`${weekly.length} payments`,`last 7 days`],["calendar-range","gold","Monthly Revenue",formatMoney(sum(monthly)),`${monthly.length} payments`,`this month`],["calendar-check-2","purple","Bookings Today",todayBookings.length,"Live","scheduled today"],["circle-check-big","green","Completed Jobs",completed.length,"Live","all records"],["clock-3","orange","Pending Jobs",store.bookings.filter(b=>["Pending","Confirmed","In Progress"].includes(b.status)).length,"Live","open jobs"],["user-round-plus","blue","Customers",store.customers.length,"Live","customer records"],["crown","purple","Active Memberships",store.memberships.filter(m=>m.status==="Active").length,"Live","current plans"],["triangle-alert","red","Low Inventory Alerts",low.length,"Restock needed","at or below minimum",true]];
  const activities=store.notifications.slice(0,4);
  return `<section class="page-transition">${pageHeader("Welcome back, Admin 👋", "Live operational data from your Command Center.", liveDateControl())}<div class="kpi-grid">${metrics.map(m=>metricCard(...m)).join("")}</div><div class="dashboard-charts"><section class="panel chart-panel"><div class="panel-header"><h2>Revenue Trend</h2><span class="subtext">Current month</span></div>${revenueChart()}</section><section class="panel chart-panel"><div class="panel-header"><h2>Booking Trend</h2><span class="subtext">Current month</span></div>${bookingChart()}</section><section class="panel chart-panel package-panel"><div class="panel-header"><h2>Popular Packages</h2></div>${donutChart()}</section></div><div class="dashboard-bottom"><section class="panel activity-panel"><div class="panel-header"><h2>Recent Activity</h2></div><div class="activity-list">${activities.map(n=>`<div class="activity-row"><span class="activity-icon gold-icon">${icon(n.icon)}</span><div class="activity-content"><p>${escapeHtml(n.title)}</p><span>${escapeHtml(n.text)}</span></div><time class="activity-time">${escapeHtml(n.time)}</time></div>`).join("") || `<div class="empty-state">No recent activity.</div>`}</div><button class="view-activity" type="button" data-page="notifications">View all activity ${icon("chevron-right")}</button></section><section class="panel quick-panel"><div class="panel-header"><h2>Quick Actions</h2></div><div class="quick-actions"><button class="quick-action" type="button" data-open-modal="booking"><span class="quick-icon">${icon("calendar-plus")}</span><span>New Booking</span></button><button class="quick-action" type="button" data-open-modal="customer"><span class="quick-icon">${icon("user-round-plus")}</span><span>Add Customer</span></button><button class="quick-action" type="button" data-open-modal="payment"><span class="quick-icon">${icon("credit-card")}</span><span>Record Payment</span></button><button class="quick-action" type="button" data-open-modal="inventory"><span class="quick-icon">${icon("box")}</span><span>Add Inventory</span></button></div></section></div></section>`;
}

function calendarPage() {
  const cursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),calendarCursor.getDate()); const title = cursor.toLocaleDateString("en-GB",{month:"long",year:"numeric"});
  const event = b => `<button class="calendar-event gold" type="button" data-action="view-booking" data-id="${b.id}">${escapeHtml(b.time)} ${escapeHtml(b.customer)}</button>`;
  const bookings=store.bookings.filter(b=>bookingDate(b));
  let body="";
  if(calendarView === "Agenda") { const rows=bookings.filter(b=>bookingDate(b)>=isoDate()).sort((a,b)=>bookingDate(a).localeCompare(bookingDate(b))); body=`<div class="activity-list">${rows.map(b=>`<div class="activity-row"><span class="metric-icon gold">${icon("calendar-check")}</span><div class="activity-content"><p><strong>${escapeHtml(b.customer)}</strong> · ${escapeHtml(b.package)}</p><span>${displayDate(b.date)} at ${escapeHtml(b.time)} · ${escapeHtml(b.vehicle)}</span></div><button class="row-action" data-action="view-booking" data-id="${b.id}">${icon("eye")}</button></div>`).join("") || `<div class="empty-state">No upcoming bookings.</div>`}</div>`; }
  else if(calendarView === "Day" || calendarView === "Week") { const start=new Date(cursor); if(calendarView === "Week") start.setDate(start.getDate()-start.getDay()); const days=calendarView==="Day"?[cursor]:Array.from({length:7},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i)); body=`<div class="calendar-grid">${days.map(d=>`<div class="calendar-day" style="min-height:260px"><span class="day-number">${d.toLocaleDateString("en-GB",{weekday:"short",day:"numeric",month:"short"})}</span>${bookings.filter(b=>b.date===isoDate(d)).sort((a,b)=>a.time.localeCompare(b.time)).map(event).join("") || `<small class="subtext">No bookings</small>`}</div>`).join("")}</div>`; }
  else { const first=new Date(cursor.getFullYear(),cursor.getMonth(),1), start=new Date(first); start.setDate(1-first.getDay()); const cells=Array.from({length:42},(_,i)=>new Date(start.getFullYear(),start.getMonth(),start.getDate()+i)); body=`<div class="calendar-grid">${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(d=>`<div class="calendar-weekday">${d}</div>`).join("")}${cells.map(d=>`<div class="calendar-day ${d.getMonth()!==cursor.getMonth()?"muted":""} ${isoDate(d)===isoDate()?"today":""}"><span class="day-number">${d.getDate()}</span>${bookings.filter(b=>b.date===isoDate(d)).map(event).join("")}</div>`).join("")}</div>`; }
  return `<section class="page-transition">${pageHeader("Calendar", "Bookings are synchronized with your live booking records.", `<button class="outline-button" type="button" data-action="today">Today</button><button class="primary-button" type="button" data-open-modal="booking">${icon("plus")} New Booking</button>`)}<section class="panel calendar-card"><div class="calendar-toolbar"><div class="calendar-nav"><button type="button" data-action="month-nav" data-direction="-1">${icon("chevron-left")}</button><h2>${calendarView === "Month" ? title : cursor.toLocaleDateString("en-GB",{day:"numeric",month:"long",year:"numeric"})}</h2><button type="button" data-action="month-nav" data-direction="1">${icon("chevron-right")}</button></div><div class="tabs" style="margin:0">${["Day","Week","Month","Agenda"].map(v=>`<button class="tab ${calendarView===v?"active":""}" type="button" data-action="calendar-view" data-view="${v}">${v}</button>`).join("")}</div></div>${body}</section></section>`;
}
